export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BYid";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER_BY_ID = "UPDATE_CUSTOMER_BYid";
export const DELETE_CUSTOMER_BY_ID = "DELETE_CUSTOMER_BYid";
export const FILTER_CUSTOMER = "FILTER_CUSTOMER";
